### ISSUE TITLE
Mesquito Installation Faliure

### ISSUE THREAD

**Issue by avnicado** [KindleModding/Mesquito#1]
Summary:
Upon installing Mesquito on my Kindle Paperwhite 3 (pw3) @ version 5.15.1.1, the Kindle store fails to respond as expected. Instead of displaying Mesquito, the standard Kindle store interface persists. Attempting to rectify the issue, I removed Kwebbrew and Mesquito, assuming the presence of two apps folders may have caused confusion. Subsequently, I reinstalled Mesquito, but the Kindle store continues to malfunction, failing to display the desired interface.

Steps to Reproduce:

Install Mesquito on Kindle Paperwhite 3 (pw3) @ version 5.15.1.1.
Open the Kindle store.
Observe that the Kindle store displays the standard interface instead of Mesquito's interface.
Access the Kindle's files to remove Kwebbrew and Mesquito.
Reinstall Mesquito on the device.
Open the Kindle store again.
Expected Results:
After installing Mesquito, opening the Kindle store should display the Mesquito interface, providing access to the additional functionalities and features.

Actual Results:
Upon launching the Kindle store after Mesquito installation, it retains the standard Kindle store interface, failing to respond to the installation of Mesquito. Even after removing Kwebbrew and Mesquito, then reinstalling Mesquito, the Kindle store still does not display the expected interface.

Additional Information:

Device: Kindle Paperwhite 3 (pw3)
Device Version: 5.15.1.1
Mesquito Version: Not specified
Kwebbrew Version: Not specified
Internet Connection: Active and stable
Impact:
The inability to access the Mesquito interface through the Kindle store impedes my ability to utilize additional features and functionalities that Mesquito offers. This issue affects the overall usability of my Kindle Paperwhite 3 (pw3).

Thank you for your prompt attention to this matter. I appreciate any efforts made to rectify the problem and ensure the proper functioning of the Kindle store with Mesquito installed. Should you require any additional information or logs, please let me know.
Note: ChatGPT was used to help formalize this issue. (I have bad writing skills.)

**Comment by Lukas1h** [comment]
Try this: Delete all Mesquito and KWebBrew related folders and files, reboot three times, and then try again.

Also, delete the .active-content folder on the root of the kindle. It's hidden, so you may have to mess around with some settings for it to show.

**Comment by avnicado** [comment]
ok

**Comment by avnicado** [comment]
it didnt work i still see the same old amazon store but there is no apps folder on the kindle should there be?

**Comment by Lukas1h** [comment]
Could you describe your process of installing Mesquito?

**Comment by avnicado** [comment]
i must have been using the wrong files or something beacause when i tried again Mesquito opened  however there are no app buttons
[wininfo_screenshot_2023_07_18T19_54_20-0400.txt](https://github.com/KindleModding/Mesquito/files/12108440/wininfo_screenshot_2023_07_18T19_54_20-0400.txt)

**Comment by avnicado** [comment]
ahh bad link sorry 
![screenshot_2023_07_18T19_54_20-0400](https://github.com/KindleModding/Mesquito/assets/102918858/fa68f59f-91ef-4c03-abbb-472d647be89f)

**Comment by ThatHackerDudeFromCyberspace** [comment]
This is a big with v0.3.0

I'm working on a fix for it

**Comment by avnicado** [comment]
Thank you. :)

**Comment by ThatHackerDudeFromCyberspace** [comment]
could you please send a screenshot of the contents of the `apps` folder on your Kindle please

**Comment by ThatHackerDudeFromCyberspace** [comment]
And also show the log when you click the `toggle log button`

**Comment by avnicado** [comment]
can i get back to you later my kindle is having water damage issues?

**Comment by avnicado** [comment]
![screenshot_2023_08_03T09_30_12-0400](https://github.com/KindleModding/Mesquito/assets/102918858/7fc7bef8-75a8-46b4-9907-8103fcccfb6d)
![Screenshot from 2023-08-03 09-29-41](https://github.com/KindleModding/Mesquito/assets/102918858/6d885f23-1dba-4d5b-ab12-8436248a63f3)

**Comment by ThatHackerDudeFromCyberspace** [comment]
Delete the microgames and scribble folders, they're currently unstable and not in the latest release

**Comment by Gustavoppw** [comment]
> i must have been using the wrong files or something beacause when i tried again Mesquito opened however there are no app buttons [wininfo_screenshot_2023_07_18T19_54_20-0400.txt](https://github.com/KindleModding/Mesquito/files/12108440/wininfo_screenshot_2023_07_18T19_54_20-0400.txt)

hey, how did you get it working? i never got mine
