### ISSUE TITLE
Scroll speed on WAFS

### ISSUE THREAD

**Issue by Aityz** [KindleModding/Mesquito#2]
I have noticed that on WAFs that I have made, the scroll speed scrolls about 1/2 of a line per swipe. Is there a way to change this?

**Comment by ThatHackerDudeFromCyberspace** [comment]
Please send WAF source

**Comment by Aityz** [comment]
I tried replicating it, and it's with every WAF I make, even on the Mesquito page. Every scroll scrolls about 1/2 of a line making reading a RSS reader I made for the Kindle incredibly hard to use.
